name: CI Pipeline

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
        - 8123:8123
        env:
          CLICKHOUSE_PASSWORD: 1234
        options: >-
          --health-cmd "wget --spider -q 'http://default:1234@localhost:8123/ping'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          curl -sSl https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: User API Install dependencies
        run: |
          poetry install --with dev
      - name: User API Run Flake8 Linter
        run: |
          poetry run flake8 . --count --show-source --statistics --max-line-length=88
      - name: Run Pytest
        run: |
          echo "API_KEY=test_key" > .env
          echo "CLICKHOUSE_HOST=localhost" >> .env
          echo "CLICKHOUSE_PORT=8123" >> .env
          echo "CLICKHOUSE_USER=default" >> .env
          echo "CLICKHOUSE_PASSWORD=1234" >> .env
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env

          poetry run pytest
      - name: Generator Install Dependencies
        run: cd generator_service && poetry install --with dev
      - name: Generator Run Flake8
        run: poetry run flake8 ./generator_service/generator --count --show-source --statistics --max-line-length=88
